import unittest
from mmstructlib.IO.cif import parse_cif, get_seq_atom_res
from test.data import get_file_path

seq1A0 = ['SER', 'SER', 'SER', 'VAL', 'PRO', 'SER', 'GLN', 'LYS', 'THR', 'TYR', 'GLN', 'GLY', 'SER', 'TYR', 'GLY', 'PHE', 'ARG', 'LEU', 'GLY', 'PHE', 'LEU', 'HIS', 'SER', 'GLY', 'THR', 'ALA', 'LYS', 'SER', 'VAL', 'THR', 'CYS', 'THR', 'TYR', 'SER', 'PRO', 'ALA', 'LEU', 'ASN', 'LYS', 'MET', 'PHE', 'CYS', 'GLN', 'LEU', 'ALA', 'LYS', 'THR', 'CYS', 'PRO', 'VAL', 'GLN', 'LEU', 'TRP', 'VAL', 'ASP', 'SER', 'THR', 'PRO', 'PRO', 'PRO', 'GLY', 'THR', 'ARG', 'VAL', 'ARG', 'ALA', 'MET', 'ALA', 'ILE', 'TYR', 'LYS', 'GLN', 'SER', 'GLN', 'HIS', 'MET', 'THR', 'GLU', 'VAL', 'VAL', 'ARG', 'ARG', 'CYS', 'PRO', 'HIS', 'HIS', 'GLU', 'ARG', 'CYS', 'SER', 'ASP', 'SER', 'ASP', 'GLY', 'LEU', 'ALA', 'PRO', 'PRO', 'GLN', 'HIS', 'LEU', 'ILE', 'ARG', 'VAL', 'GLU', 'GLY', 'ASN', 'LEU', 'ARG', 'VAL', 'GLU', 'TYR', 'LEU', 'ASP', 'ASP', 'ARG', 'ASN', 'THR', 'PHE', 'ARG', 'HIS', 'SER', 'VAL', 'VAL', 'VAL', 'PRO', 'TYR', 'GLU', 'PRO', 'PRO', 'GLU', 'VAL', 'GLY', 'SER', 'ASP', 'CYS', 'THR', 'THR', 'ILE', 'HIS', 'TYR', 'ASN', 'TYR', 'MET', 'CYS', 'ASN', 'SER', 'SER', 'CYS', 'MET', 'GLY', 'GLY', 'MET', 'ASN', 'ARG', 'ARG', 'PRO', 'ILE', 'LEU', 'THR', 'ILE', 'ILE', 'THR', 'LEU', 'GLU', 'ASP', 'SER', 'SER', 'GLY', 'ASN', 'LEU', 'LEU', 'GLY', 'ARG', 'ASN', 'SER', 'PHE', 'GLU', 'VAL', 'ARG', 'VAL', 'CYS', 'ALA', 'CYS', 'PRO', 'GLY', 'ARG', 'ASP', 'ARG', 'ARG', 'THR', 'GLU', 'GLU', 'GLU', 'ASN', 'LEU', 'ARG', 'LYS', 'LYS', 'GLY', 'GLU', 'PRO', 'HIS', 'HIS', 'GLU', 'LEU', 'PRO', 'PRO', 'GLY', 'SER', 'THR', 'LYS', 'ARG', 'ALA', 'LEU', 'PRO', 'ASN', 'ASN', 'THR']
seq1A1 = [None, None, 'SER', 'VAL', 'PRO', 'SER', 'GLN', 'LYS', 'THR', 'TYR', 'GLN', 'GLY', 'SER', 'TYR', 'GLY', 'PHE', 'ARG', 'LEU', 'GLY', 'PHE', 'LEU', 'HIS', 'SER', 'GLY', 'THR', 'ALA', 'LYS', 'SER', 'VAL', 'THR', 'CYS', 'THR', 'TYR', 'SER', 'PRO', 'ALA', 'LEU', 'ASN', 'LYS', 'MET', 'PHE', 'CYS', 'GLN', 'LEU', 'ALA', 'LYS', 'THR', 'CYS', 'PRO', 'VAL', 'GLN', 'LEU', 'TRP', 'VAL', 'ASP', 'SER', 'THR', 'PRO', 'PRO', 'PRO', 'GLY', 'THR', 'ARG', 'VAL', 'ARG', 'ALA', 'MET', 'ALA', 'ILE', 'TYR', 'LYS', 'GLN', 'SER', 'GLN', 'HIS', 'MET', 'THR', 'GLU', 'VAL', 'VAL', 'ARG', 'ARG', 'CYS', 'PRO', 'HIS', 'HIS', 'GLU', 'ARG', 'CYS', 'SER', 'ASP', 'SER', 'ASP', 'GLY', 'LEU', 'ALA', 'PRO', 'PRO', 'GLN', 'HIS', 'LEU', 'ILE', 'ARG', 'VAL', 'GLU', 'GLY', 'ASN', 'LEU', 'ARG', 'VAL', 'GLU', 'TYR', 'LEU', 'ASP', 'ASP', 'ARG', 'ASN', 'THR', 'PHE', 'ARG', 'HIS', 'SER', 'VAL', 'VAL', 'VAL', 'PRO', 'TYR', 'GLU', 'PRO', 'PRO', 'GLU', 'VAL', 'GLY', 'SER', 'ASP', 'CYS', 'THR', 'THR', 'ILE', 'HIS', 'TYR', 'ASN', 'TYR', 'MET', 'CYS', 'ASN', 'SER', 'SER', 'CYS', 'MET', 'GLY', 'GLY', 'MET', 'ASN', 'ARG', 'ARG', 'PRO', 'ILE', 'LEU', 'THR', 'ILE', 'ILE', 'THR', 'LEU', 'GLU', 'ASP', 'SER', 'SER', 'GLY', 'ASN', 'LEU', 'LEU', 'GLY', 'ARG', 'ASN', 'SER', 'PHE', 'GLU', 'VAL', 'ARG', 'VAL', 'CYS', 'ALA', 'CYS', 'PRO', 'GLY', 'ARG', 'ASP', 'ARG', 'ARG', 'THR', 'GLU', 'GLU', 'GLU', 'ASN', 'LEU', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]

seq1B0 = ['SER', 'SER', 'SER', 'VAL', 'PRO', 'SER', 'GLN', 'LYS', 'THR', 'TYR', 'GLN', 'GLY', 'SER', 'TYR', 'GLY', 'PHE', 'ARG', 'LEU', 'GLY', 'PHE', 'LEU', 'HIS', 'SER', 'GLY', 'THR', 'ALA', 'LYS', 'SER', 'VAL', 'THR', 'CYS', 'THR', 'TYR', 'SER', 'PRO', 'ALA', 'LEU', 'ASN', 'LYS', 'MET', 'PHE', 'CYS', 'GLN', 'LEU', 'ALA', 'LYS', 'THR', 'CYS', 'PRO', 'VAL', 'GLN', 'LEU', 'TRP', 'VAL', 'ASP', 'SER', 'THR', 'PRO', 'PRO', 'PRO', 'GLY', 'THR', 'ARG', 'VAL', 'ARG', 'ALA', 'MET', 'ALA', 'ILE', 'TYR', 'LYS', 'GLN', 'SER', 'GLN', 'HIS', 'MET', 'THR', 'GLU', 'VAL', 'VAL', 'ARG', 'ARG', 'CYS', 'PRO', 'HIS', 'HIS', 'GLU', 'ARG', 'CYS', 'SER', 'ASP', 'SER', 'ASP', 'GLY', 'LEU', 'ALA', 'PRO', 'PRO', 'GLN', 'HIS', 'LEU', 'ILE', 'ARG', 'VAL', 'GLU', 'GLY', 'ASN', 'LEU', 'ARG', 'VAL', 'GLU', 'TYR', 'LEU', 'ASP', 'ASP', 'ARG', 'ASN', 'THR', 'PHE', 'ARG', 'HIS', 'SER', 'VAL', 'VAL', 'VAL', 'PRO', 'TYR', 'GLU', 'PRO', 'PRO', 'GLU', 'VAL', 'GLY', 'SER', 'ASP', 'CYS', 'THR', 'THR', 'ILE', 'HIS', 'TYR', 'ASN', 'TYR', 'MET', 'CYS', 'ASN', 'SER', 'SER', 'CYS', 'MET', 'GLY', 'GLY', 'MET', 'ASN', 'ARG', 'ARG', 'PRO', 'ILE', 'LEU', 'THR', 'ILE', 'ILE', 'THR', 'LEU', 'GLU', 'ASP', 'SER', 'SER', 'GLY', 'ASN', 'LEU', 'LEU', 'GLY', 'ARG', 'ASN', 'SER', 'PHE', 'GLU', 'VAL', 'ARG', 'VAL', 'CYS', 'ALA', 'CYS', 'PRO', 'GLY', 'ARG', 'ASP', 'ARG', 'ARG', 'THR', 'GLU', 'GLU', 'GLU', 'ASN', 'LEU', 'ARG', 'LYS', 'LYS', 'GLY', 'GLU', 'PRO', 'HIS', 'HIS', 'GLU', 'LEU', 'PRO', 'PRO', 'GLY', 'SER', 'THR', 'LYS', 'ARG', 'ALA', 'LEU', 'PRO', 'ASN', 'ASN', 'THR']
seq1B1 = [None, None, 'SER', 'VAL', 'PRO', 'SER', 'GLN', 'LYS', 'THR', 'TYR', 'GLN', 'GLY', 'SER', 'TYR', 'GLY', 'PHE', 'ARG', 'LEU', 'GLY', 'PHE', 'LEU', 'HIS', 'SER', 'GLY', 'THR', 'ALA', 'LYS', 'SER', 'VAL', 'THR', 'CYS', 'THR', 'TYR', 'SER', 'PRO', 'ALA', 'LEU', 'ASN', 'LYS', 'MET', 'PHE', 'CYS', 'GLN', 'LEU', 'ALA', 'LYS', 'THR', 'CYS', 'PRO', 'VAL', 'GLN', 'LEU', 'TRP', 'VAL', 'ASP', 'SER', 'THR', 'PRO', 'PRO', 'PRO', 'GLY', 'THR', 'ARG', 'VAL', 'ARG', 'ALA', 'MET', 'ALA', 'ILE', 'TYR', 'LYS', 'GLN', 'SER', 'GLN', 'HIS', 'MET', 'THR', 'GLU', 'VAL', 'VAL', 'ARG', 'ARG', 'CYS', 'PRO', 'HIS', 'HIS', 'GLU', 'ARG', 'CYS', 'SER', 'ASP', 'SER', 'ASP', 'GLY', 'LEU', 'ALA', 'PRO', 'PRO', 'GLN', 'HIS', 'LEU', 'ILE', 'ARG', 'VAL', 'GLU', 'GLY', 'ASN', 'LEU', 'ARG', 'VAL', 'GLU', 'TYR', 'LEU', 'ASP', 'ASP', 'ARG', 'ASN', 'THR', 'PHE', 'ARG', 'HIS', 'SER', 'VAL', 'VAL', 'VAL', 'PRO', 'TYR', 'GLU', 'PRO', 'PRO', 'GLU', 'VAL', 'GLY', 'SER', 'ASP', 'CYS', 'THR', 'THR', 'ILE', 'HIS', 'TYR', 'ASN', 'TYR', 'MET', 'CYS', 'ASN', 'SER', 'SER', 'CYS', 'MET', 'GLY', 'GLY', 'MET', 'ASN', 'ARG', 'ARG', 'PRO', 'ILE', 'LEU', 'THR', 'ILE', 'ILE', 'THR', 'LEU', 'GLU', 'ASP', 'SER', 'SER', 'GLY', 'ASN', 'LEU', 'LEU', 'GLY', 'ARG', 'ASN', 'SER', 'PHE', 'GLU', 'VAL', 'ARG', 'VAL', 'CYS', 'ALA', 'CYS', 'PRO', 'GLY', 'ARG', 'ASP', 'ARG', 'ARG', 'THR', 'GLU', 'GLU', 'GLU', 'ASN', 'LEU', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]

seq1C0 = ['SER', 'SER', 'SER', 'VAL', 'PRO', 'SER', 'GLN', 'LYS', 'THR', 'TYR', 'GLN', 'GLY', 'SER', 'TYR', 'GLY', 'PHE', 'ARG', 'LEU', 'GLY', 'PHE', 'LEU', 'HIS', 'SER', 'GLY', 'THR', 'ALA', 'LYS', 'SER', 'VAL', 'THR', 'CYS', 'THR', 'TYR', 'SER', 'PRO', 'ALA', 'LEU', 'ASN', 'LYS', 'MET', 'PHE', 'CYS', 'GLN', 'LEU', 'ALA', 'LYS', 'THR', 'CYS', 'PRO', 'VAL', 'GLN', 'LEU', 'TRP', 'VAL', 'ASP', 'SER', 'THR', 'PRO', 'PRO', 'PRO', 'GLY', 'THR', 'ARG', 'VAL', 'ARG', 'ALA', 'MET', 'ALA', 'ILE', 'TYR', 'LYS', 'GLN', 'SER', 'GLN', 'HIS', 'MET', 'THR', 'GLU', 'VAL', 'VAL', 'ARG', 'ARG', 'CYS', 'PRO', 'HIS', 'HIS', 'GLU', 'ARG', 'CYS', 'SER', 'ASP', 'SER', 'ASP', 'GLY', 'LEU', 'ALA', 'PRO', 'PRO', 'GLN', 'HIS', 'LEU', 'ILE', 'ARG', 'VAL', 'GLU', 'GLY', 'ASN', 'LEU', 'ARG', 'VAL', 'GLU', 'TYR', 'LEU', 'ASP', 'ASP', 'ARG', 'ASN', 'THR', 'PHE', 'ARG', 'HIS', 'SER', 'VAL', 'VAL', 'VAL', 'PRO', 'TYR', 'GLU', 'PRO', 'PRO', 'GLU', 'VAL', 'GLY', 'SER', 'ASP', 'CYS', 'THR', 'THR', 'ILE', 'HIS', 'TYR', 'ASN', 'TYR', 'MET', 'CYS', 'ASN', 'SER', 'SER', 'CYS', 'MET', 'GLY', 'GLY', 'MET', 'ASN', 'ARG', 'ARG', 'PRO', 'ILE', 'LEU', 'THR', 'ILE', 'ILE', 'THR', 'LEU', 'GLU', 'ASP', 'SER', 'SER', 'GLY', 'ASN', 'LEU', 'LEU', 'GLY', 'ARG', 'ASN', 'SER', 'PHE', 'GLU', 'VAL', 'ARG', 'VAL', 'CYS', 'ALA', 'CYS', 'PRO', 'GLY', 'ARG', 'ASP', 'ARG', 'ARG', 'THR', 'GLU', 'GLU', 'GLU', 'ASN', 'LEU', 'ARG', 'LYS', 'LYS', 'GLY', 'GLU', 'PRO', 'HIS', 'HIS', 'GLU', 'LEU', 'PRO', 'PRO', 'GLY', 'SER', 'THR', 'LYS', 'ARG', 'ALA', 'LEU', 'PRO', 'ASN', 'ASN', 'THR']
seq1C1 = [None, None, 'SER', 'VAL', 'PRO', 'SER', 'GLN', 'LYS', 'THR', 'TYR', 'GLN', 'GLY', 'SER', 'TYR', 'GLY', 'PHE', 'ARG', 'LEU', 'GLY', 'PHE', 'LEU', 'HIS', 'SER', 'GLY', 'THR', 'ALA', 'LYS', 'SER', 'VAL', 'THR', 'CYS', 'THR', 'TYR', 'SER', 'PRO', 'ALA', 'LEU', 'ASN', 'LYS', 'MET', 'PHE', 'CYS', 'GLN', 'LEU', 'ALA', 'LYS', 'THR', 'CYS', 'PRO', 'VAL', 'GLN', 'LEU', 'TRP', 'VAL', 'ASP', 'SER', 'THR', 'PRO', 'PRO', 'PRO', 'GLY', 'THR', 'ARG', 'VAL', 'ARG', 'ALA', 'MET', 'ALA', 'ILE', 'TYR', 'LYS', 'GLN', 'SER', 'GLN', 'HIS', 'MET', 'THR', 'GLU', 'VAL', 'VAL', 'ARG', 'ARG', 'CYS', 'PRO', 'HIS', 'HIS', 'GLU', 'ARG', 'CYS', 'SER', 'ASP', 'SER', 'ASP', 'GLY', 'LEU', 'ALA', 'PRO', 'PRO', 'GLN', 'HIS', 'LEU', 'ILE', 'ARG', 'VAL', 'GLU', 'GLY', 'ASN', 'LEU', 'ARG', 'VAL', 'GLU', 'TYR', 'LEU', 'ASP', 'ASP', 'ARG', 'ASN', 'THR', 'PHE', 'ARG', 'HIS', 'SER', 'VAL', 'VAL', 'VAL', 'PRO', 'TYR', 'GLU', 'PRO', 'PRO', 'GLU', 'VAL', 'GLY', 'SER', 'ASP', 'CYS', 'THR', 'THR', 'ILE', 'HIS', 'TYR', 'ASN', 'TYR', 'MET', 'CYS', 'ASN', 'SER', 'SER', 'CYS', 'MET', 'GLY', 'GLY', 'MET', 'ASN', 'ARG', 'ARG', 'PRO', 'ILE', 'LEU', 'THR', 'ILE', 'ILE', 'THR', 'LEU', 'GLU', 'ASP', 'SER', 'SER', 'GLY', 'ASN', 'LEU', 'LEU', 'GLY', 'ARG', 'ASN', 'SER', 'PHE', 'GLU', 'VAL', 'ARG', 'VAL', 'CYS', 'ALA', 'CYS', 'PRO', 'GLY', 'ARG', 'ASP', 'ARG', 'ARG', 'THR', 'GLU', 'GLU', 'GLU', 'ASN', 'LEU', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]

seq1D0 = ['SER', 'SER', 'SER', 'VAL', 'PRO', 'SER', 'GLN', 'LYS', 'THR', 'TYR', 'GLN', 'GLY', 'SER', 'TYR', 'GLY', 'PHE', 'ARG', 'LEU', 'GLY', 'PHE', 'LEU', 'HIS', 'SER', 'GLY', 'THR', 'ALA', 'LYS', 'SER', 'VAL', 'THR', 'CYS', 'THR', 'TYR', 'SER', 'PRO', 'ALA', 'LEU', 'ASN', 'LYS', 'MET', 'PHE', 'CYS', 'GLN', 'LEU', 'ALA', 'LYS', 'THR', 'CYS', 'PRO', 'VAL', 'GLN', 'LEU', 'TRP', 'VAL', 'ASP', 'SER', 'THR', 'PRO', 'PRO', 'PRO', 'GLY', 'THR', 'ARG', 'VAL', 'ARG', 'ALA', 'MET', 'ALA', 'ILE', 'TYR', 'LYS', 'GLN', 'SER', 'GLN', 'HIS', 'MET', 'THR', 'GLU', 'VAL', 'VAL', 'ARG', 'ARG', 'CYS', 'PRO', 'HIS', 'HIS', 'GLU', 'ARG', 'CYS', 'SER', 'ASP', 'SER', 'ASP', 'GLY', 'LEU', 'ALA', 'PRO', 'PRO', 'GLN', 'HIS', 'LEU', 'ILE', 'ARG', 'VAL', 'GLU', 'GLY', 'ASN', 'LEU', 'ARG', 'VAL', 'GLU', 'TYR', 'LEU', 'ASP', 'ASP', 'ARG', 'ASN', 'THR', 'PHE', 'ARG', 'HIS', 'SER', 'VAL', 'VAL', 'VAL', 'PRO', 'TYR', 'GLU', 'PRO', 'PRO', 'GLU', 'VAL', 'GLY', 'SER', 'ASP', 'CYS', 'THR', 'THR', 'ILE', 'HIS', 'TYR', 'ASN', 'TYR', 'MET', 'CYS', 'ASN', 'SER', 'SER', 'CYS', 'MET', 'GLY', 'GLY', 'MET', 'ASN', 'ARG', 'ARG', 'PRO', 'ILE', 'LEU', 'THR', 'ILE', 'ILE', 'THR', 'LEU', 'GLU', 'ASP', 'SER', 'SER', 'GLY', 'ASN', 'LEU', 'LEU', 'GLY', 'ARG', 'ASN', 'SER', 'PHE', 'GLU', 'VAL', 'ARG', 'VAL', 'CYS', 'ALA', 'CYS', 'PRO', 'GLY', 'ARG', 'ASP', 'ARG', 'ARG', 'THR', 'GLU', 'GLU', 'GLU', 'ASN', 'LEU', 'ARG', 'LYS', 'LYS', 'GLY', 'GLU', 'PRO', 'HIS', 'HIS', 'GLU', 'LEU', 'PRO', 'PRO', 'GLY', 'SER', 'THR', 'LYS', 'ARG', 'ALA', 'LEU', 'PRO', 'ASN', 'ASN', 'THR']
seq1D1 = [None, None, 'SER', 'VAL', 'PRO', 'SER', 'GLN', 'LYS', 'THR', 'TYR', 'GLN', 'GLY', 'SER', 'TYR', 'GLY', 'PHE', 'ARG', 'LEU', 'GLY', 'PHE', 'LEU', 'HIS', 'SER', 'GLY', 'THR', 'ALA', 'LYS', 'SER', 'VAL', 'THR', 'CYS', 'THR', 'TYR', 'SER', 'PRO', 'ALA', 'LEU', 'ASN', 'LYS', 'MET', 'PHE', 'CYS', 'GLN', 'LEU', 'ALA', 'LYS', 'THR', 'CYS', 'PRO', 'VAL', 'GLN', 'LEU', 'TRP', 'VAL', 'ASP', 'SER', 'THR', 'PRO', 'PRO', 'PRO', 'GLY', 'THR', 'ARG', 'VAL', 'ARG', 'ALA', 'MET', 'ALA', 'ILE', 'TYR', 'LYS', 'GLN', 'SER', 'GLN', 'HIS', 'MET', 'THR', 'GLU', 'VAL', 'VAL', 'ARG', 'ARG', 'CYS', 'PRO', 'HIS', 'HIS', 'GLU', 'ARG', 'CYS', 'SER', 'ASP', 'SER', 'ASP', 'GLY', 'LEU', 'ALA', 'PRO', 'PRO', 'GLN', 'HIS', 'LEU', 'ILE', 'ARG', 'VAL', 'GLU', 'GLY', 'ASN', 'LEU', 'ARG', 'VAL', 'GLU', 'TYR', 'LEU', 'ASP', 'ASP', 'ARG', 'ASN', 'THR', 'PHE', 'ARG', 'HIS', 'SER', 'VAL', 'VAL', 'VAL', 'PRO', 'TYR', 'GLU', 'PRO', 'PRO', 'GLU', 'VAL', 'GLY', 'SER', 'ASP', 'CYS', 'THR', 'THR', 'ILE', 'HIS', 'TYR', 'ASN', 'TYR', 'MET', 'CYS', 'ASN', 'SER', 'SER', 'CYS', 'MET', 'GLY', 'GLY', 'MET', 'ASN', 'ARG', 'ARG', 'PRO', 'ILE', 'LEU', 'THR', 'ILE', 'ILE', 'THR', 'LEU', 'GLU', 'ASP', 'SER', 'SER', 'GLY', 'ASN', 'LEU', 'LEU', 'GLY', 'ARG', 'ASN', 'SER', 'PHE', 'GLU', 'VAL', 'ARG', 'VAL', 'CYS', 'ALA', 'CYS', 'PRO', 'GLY', 'ARG', 'ASP', 'ARG', 'ARG', 'THR', 'GLU', 'GLU', 'GLU', 'ASN', 'LEU', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]

seq2A0 = ['SER', 'HIS', 'LEU', 'LYS', 'SER', 'LYS', 'LYS', 'GLY', 'GLN', 'SER', 'THR', 'SER', 'ARG', 'HIS', 'LYS', 'ALY', 'LEU', 'MET', 'PHE', 'LYS']
seq2A1 = ['SER', 'HIS', 'LEU', 'LYS', 'SER', 'LYS', 'LYS', 'GLY', 'GLN', 'SER', 'THR', 'SER', 'ARG', 'HIS', 'LYS', 'ALY', 'LEU', 'MET', 'PHE', 'LYS']

seq2B0 = ['GLY', 'SER', 'HIS', 'MET', 'ARG', 'LYS', 'LYS', 'ILE', 'PHE', 'LYS', 'PRO', 'GLU', 'GLU', 'LEU', 'ARG', 'GLN', 'ALA', 'LEU', 'MET', 'PRO', 'THR', 'LEU', 'GLU', 'ALA', 'LEU', 'TYR', 'ARG', 'GLN', 'ASP', 'PRO', 'GLU', 'SER', 'LEU', 'PRO', 'PHE', 'ARG', 'GLN', 'PRO', 'VAL', 'ASP', 'PRO', 'GLN', 'LEU', 'LEU', 'GLY', 'ILE', 'PRO', 'ASP', 'TYR', 'PHE', 'ASP', 'ILE', 'VAL', 'LYS', 'ASN', 'PRO', 'MET', 'ASP', 'LEU', 'SER', 'THR', 'ILE', 'LYS', 'ARG', 'LYS', 'LEU', 'ASP', 'THR', 'GLY', 'GLN', 'TYR', 'GLN', 'GLU', 'PRO', 'TRP', 'GLN', 'TYR', 'VAL', 'ASP', 'ASP', 'VAL', 'TRP', 'LEU', 'MET', 'PHE', 'ASN', 'ASN', 'ALA', 'TRP', 'LEU', 'TYR', 'ASN', 'ARG', 'LYS', 'THR', 'SER', 'ARG', 'VAL', 'TYR', 'LYS', 'PHE', 'CYS', 'SER', 'LYS', 'LEU', 'ALA', 'GLU', 'VAL', 'PHE', 'GLU', 'GLN', 'GLU', 'ILE', 'ASP', 'PRO', 'VAL', 'MET', 'GLN', 'SER', 'LEU', 'GLY']
seq2B1 = ['GLY', 'SER', 'HIS', 'MET', 'ARG', 'LYS', 'LYS', 'ILE', 'PHE', 'LYS', 'PRO', 'GLU', 'GLU', 'LEU', 'ARG', 'GLN', 'ALA', 'LEU', 'MET', 'PRO', 'THR', 'LEU', 'GLU', 'ALA', 'LEU', 'TYR', 'ARG', 'GLN', 'ASP', 'PRO', 'GLU', 'SER', 'LEU', 'PRO', 'PHE', 'ARG', 'GLN', 'PRO', 'VAL', 'ASP', 'PRO', 'GLN', 'LEU', 'LEU', 'GLY', 'ILE', 'PRO', 'ASP', 'TYR', 'PHE', 'ASP', 'ILE', 'VAL', 'LYS', 'ASN', 'PRO', 'MET', 'ASP', 'LEU', 'SER', 'THR', 'ILE', 'LYS', 'ARG', 'LYS', 'LEU', 'ASP', 'THR', 'GLY', 'GLN', 'TYR', 'GLN', 'GLU', 'PRO', 'TRP', 'GLN', 'TYR', 'VAL', 'ASP', 'ASP', 'VAL', 'TRP', 'LEU', 'MET', 'PHE', 'ASN', 'ASN', 'ALA', 'TRP', 'LEU', 'TYR', 'ASN', 'ARG', 'LYS', 'THR', 'SER', 'ARG', 'VAL', 'TYR', 'LYS', 'PHE', 'CYS', 'SER', 'LYS', 'LEU', 'ALA', 'GLU', 'VAL', 'PHE', 'GLU', 'GLN', 'GLU', 'ILE', 'ASP', 'PRO', 'VAL', 'MET', 'GLN', 'SER', 'LEU', 'GLY']

class TestCifBuildStructure(unittest.TestCase):
    "CIF parser"
    def setUp(self):
        pass
    def tearDown(self):
        pass
    def test_run_build_structure1(self):
        with open(get_file_path("2OCJ.cif"), "rb") as fh:
            tables = parse_cif(fh)
        rowDict = get_seq_atom_res(tables)
        self.assertEqual(type(rowDict), dict)
        self.assertEqual(sorted(rowDict.keys()), ['A', 'B', 'C', 'D'])
        self.assertEqual(rowDict['A'][0], seq1A0)
        self.assertEqual(rowDict['A'][1], seq1A1)
        self.assertEqual(rowDict['B'][0], seq1B0)
        self.assertEqual(rowDict['B'][1], seq1B1)
        self.assertEqual(rowDict['C'][0], seq1C0)
        self.assertEqual(rowDict['C'][1], seq1C1)
        self.assertEqual(rowDict['D'][0], seq1D0)
        self.assertEqual(rowDict['D'][1], seq1D1)
    def test_run_build_structure2(self):
        with open(get_file_path("1JSP.cif"), "rb") as fh:
            tables = parse_cif(fh)
        rowDict = get_seq_atom_res(tables)
        self.assertEqual(type(rowDict), dict)
        self.assertEqual(sorted(rowDict.keys()), ['A', 'B'])
        self.assertEqual(rowDict['A'][0], seq2A0)
        self.assertEqual(rowDict['A'][1], seq2A1)
        self.assertEqual(rowDict['B'][0], seq2B0)
        self.assertEqual(rowDict['B'][1], seq2B1)

if __name__ == '__main__':
    unittest.main()

